name: Integración Continua

on:
    push:
        branches: ["main", "master"]

jobs:
    testeo:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: Acerautos2026*
                    MYSQL_DATABASE: acerautos_proyecto
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            - name: Obtener el codigo
              uses: actions/checkout@v4

            - name: configurar python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: instalar dependencias
              run: |
                cd sena
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-django

            - name: ejecutar pruebas
              env:
                DB_NAME: acerautos_proyecto
                DB_USER: root
                DB_PASSWORD: Acerautos2026*
                DB_HOST: 127.0.0.1
                DB_PORT: 3306
              run: |
                cd sena
                pytest app/tests.py --ds=sena.settings